-- ============================================================
-- 13_product_extras.sql
-- Mở rộng cho tính năng "thêm sản phẩm / chi tiết sản phẩm":
--   - PRODUCT_OPTION: thêm cấu hình loại chọn, mô tả, bắt buộc/hiển thị, thứ tự
--   - OPTION_VALUE: thêm phụ phí riêng theo giá trị, mặc định, kích hoạt, thứ tự
--   - PRODUCT_PROMOTION: khuyến mãi đi kèm theo từng sản phẩm (vd: "Tặng chuột")
--   - PRODUCT_BUNDLE: sản phẩm gợi ý mua kèm
-- ============================================================
USE ShopDB;
GO

-- ===== PRODUCT_OPTION =====
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PRODUCT_OPTION' AND COLUMN_NAME='selection_type')
    ALTER TABLE PRODUCT_OPTION ADD selection_type VARCHAR(20) NOT NULL DEFAULT 'single';
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PRODUCT_OPTION' AND COLUMN_NAME='min_select')
    ALTER TABLE PRODUCT_OPTION ADD min_select INT NOT NULL DEFAULT 0;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PRODUCT_OPTION' AND COLUMN_NAME='max_select')
    ALTER TABLE PRODUCT_OPTION ADD max_select INT NOT NULL DEFAULT 1;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PRODUCT_OPTION' AND COLUMN_NAME='description')
    ALTER TABLE PRODUCT_OPTION ADD description NVARCHAR(500) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PRODUCT_OPTION' AND COLUMN_NAME='is_required')
    ALTER TABLE PRODUCT_OPTION ADD is_required BIT NOT NULL DEFAULT 0;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PRODUCT_OPTION' AND COLUMN_NAME='is_visible')
    ALTER TABLE PRODUCT_OPTION ADD is_visible BIT NOT NULL DEFAULT 1;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PRODUCT_OPTION' AND COLUMN_NAME='sort_order')
    ALTER TABLE PRODUCT_OPTION ADD sort_order INT NOT NULL DEFAULT 0;
GO

-- ===== OPTION_VALUE =====
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OPTION_VALUE' AND COLUMN_NAME='price_extra')
    ALTER TABLE OPTION_VALUE ADD price_extra DECIMAL(18,2) NOT NULL DEFAULT 0;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OPTION_VALUE' AND COLUMN_NAME='is_default')
    ALTER TABLE OPTION_VALUE ADD is_default BIT NOT NULL DEFAULT 0;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OPTION_VALUE' AND COLUMN_NAME='is_active')
    ALTER TABLE OPTION_VALUE ADD is_active BIT NOT NULL DEFAULT 1;
GO
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='OPTION_VALUE' AND COLUMN_NAME='sort_order')
    ALTER TABLE OPTION_VALUE ADD sort_order INT NOT NULL DEFAULT 0;
GO

-- ===== PRODUCT_PROMOTION =====
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PRODUCT_PROMOTION')
BEGIN
    CREATE TABLE PRODUCT_PROMOTION (
        id         INT IDENTITY(1,1) PRIMARY KEY,
        product_id INT NOT NULL,
        content    NVARCHAR(1000) NOT NULL,
        sort_order INT NOT NULL DEFAULT 0,
        FOREIGN KEY (product_id) REFERENCES PRODUCT(id)
    );
    PRINT N'✅ Đã tạo bảng PRODUCT_PROMOTION';
END
ELSE
    PRINT N'⚠ Bảng PRODUCT_PROMOTION đã tồn tại, bỏ qua';
GO

-- ===== PRODUCT_BUNDLE (sản phẩm gợi ý mua kèm) =====
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PRODUCT_BUNDLE')
BEGIN
    CREATE TABLE PRODUCT_BUNDLE (
        id                 INT IDENTITY(1,1) PRIMARY KEY,
        product_id         INT NOT NULL,
        bundle_product_id  INT NOT NULL,
        FOREIGN KEY (product_id) REFERENCES PRODUCT(id),
        FOREIGN KEY (bundle_product_id) REFERENCES PRODUCT(id)
    );
    PRINT N'✅ Đã tạo bảng PRODUCT_BUNDLE';
END
ELSE
    PRINT N'⚠ Bảng PRODUCT_BUNDLE đã tồn tại, bỏ qua';
GO
