-- 46_pc_case_mainboard_cooler.sql
-- Sinh dữ liệu Mainboard/Vỏ case/Tản nhiệt cho các PC dựng sẵn — trước đó gần như trống,
-- cần có để làm bộ lọc "cấu hình" (CPU + case/mainboard/tản nhiệt) ở trang danh mục PC.
-- Chipset mainboard được chọn khớp với CPU thật của từng sản phẩm (theo socket/thế hệ).

INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (20, N'Mainboard', N'ASUS B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (20, N'Vỏ case', N'Aigo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (20, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (21, N'Mainboard', N'MSI B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (21, N'Vỏ case', N'Xigmatek', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (21, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (22, N'Mainboard', N'Gigabyte B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (22, N'Vỏ case', N'DarkFlash', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (22, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (23, N'Mainboard', N'ASRock B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (23, N'Vỏ case', N'Corsair', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (23, N'Tản nhiệt', N'ID-Cooling SE-224', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (56, N'Mainboard', N'ASUS B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (56, N'Vỏ case', N'Xigmatek', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (56, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (57, N'Mainboard', N'MSI B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (57, N'Vỏ case', N'DarkFlash', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (57, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (58, N'Mainboard', N'Gigabyte B650', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (58, N'Vỏ case', N'Corsair', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (58, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (59, N'Mainboard', N'ASRock B650', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (59, N'Vỏ case', N'Cooler Master', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (59, N'Tản nhiệt', N'ID-Cooling SE-224', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (60, N'Mainboard', N'ASUS B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (60, N'Vỏ case', N'Jonsbo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (60, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (61, N'Mainboard', N'MSI B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (61, N'Vỏ case', N'Vitra', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (61, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (62, N'Mainboard', N'Gigabyte B650', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (62, N'Vỏ case', N'Aigo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (62, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (63, N'Mainboard', N'ASRock B650', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (63, N'Vỏ case', N'Xigmatek', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (63, N'Tản nhiệt', N'ID-Cooling SE-224', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (332, N'Mainboard', N'ASUS B550', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (332, N'Vỏ case', N'Cooler Master', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (332, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (333, N'Mainboard', N'MSI B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (333, N'Vỏ case', N'Jonsbo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (333, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (334, N'Mainboard', N'Gigabyte A520', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (334, N'Vỏ case', N'Vitra', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (334, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (335, N'Mainboard', N'ASRock B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (335, N'Vỏ case', N'Aigo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (335, N'Tản nhiệt', N'ID-Cooling SE-224', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (336, N'Mainboard', N'ASUS B550', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (336, N'Vỏ case', N'Xigmatek', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (336, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (337, N'Mainboard', N'MSI B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (337, N'Vỏ case', N'DarkFlash', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (337, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (338, N'Mainboard', N'Gigabyte B650', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (338, N'Vỏ case', N'Corsair', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (338, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (339, N'Mainboard', N'ASRock B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (339, N'Vỏ case', N'Cooler Master', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (339, N'Tản nhiệt', N'ID-Cooling SE-224', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (340, N'Mainboard', N'ASUS B650', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (340, N'Vỏ case', N'Jonsbo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (340, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (341, N'Mainboard', N'MSI B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (341, N'Vỏ case', N'Vitra', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (341, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (342, N'Mainboard', N'Gigabyte B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (342, N'Vỏ case', N'Aigo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (342, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (343, N'Mainboard', N'ASRock X670', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (343, N'Vỏ case', N'Xigmatek', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (343, N'Tản nhiệt', N'Thermalright Frozen Warframe 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (344, N'Mainboard', N'ASUS Z790', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (344, N'Vỏ case', N'DarkFlash', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (344, N'Tản nhiệt', N'ID-Cooling FROZN 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (345, N'Mainboard', N'MSI B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (345, N'Vỏ case', N'Corsair', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (345, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (346, N'Mainboard', N'Gigabyte A520', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (346, N'Vỏ case', N'Cooler Master', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (346, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (347, N'Mainboard', N'ASRock B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (347, N'Vỏ case', N'Jonsbo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (347, N'Tản nhiệt', N'ID-Cooling SE-224', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (348, N'Mainboard', N'ASUS B550', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (348, N'Vỏ case', N'Vitra', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (348, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (349, N'Mainboard', N'MSI B650', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (349, N'Vỏ case', N'Aigo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (349, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (350, N'Mainboard', N'Gigabyte B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (350, N'Vỏ case', N'Xigmatek', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (350, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (351, N'Mainboard', N'ASRock X670', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (351, N'Vỏ case', N'DarkFlash', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (351, N'Tản nhiệt', N'Thermalright Frozen Warframe 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (730, N'Mainboard', N'Gigabyte A520', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (730, N'Vỏ case', N'Corsair', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (730, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (731, N'Mainboard', N'ASRock B560', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (731, N'Vỏ case', N'Cooler Master', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (731, N'Tản nhiệt', N'ID-Cooling SE-224', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (732, N'Mainboard', N'ASUS A520', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (732, N'Vỏ case', N'Jonsbo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (732, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (733, N'Mainboard', N'MSI B560', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (733, N'Vỏ case', N'Vitra', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (733, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (734, N'Mainboard', N'Gigabyte B550', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (734, N'Vỏ case', N'Aigo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (734, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (735, N'Mainboard', N'ASRock B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (735, N'Vỏ case', N'Xigmatek', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (735, N'Tản nhiệt', N'ID-Cooling SE-224', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (736, N'Mainboard', N'ASUS B650', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (736, N'Vỏ case', N'DarkFlash', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (736, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (737, N'Mainboard', N'MSI Z790', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (737, N'Vỏ case', N'Corsair', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (737, N'Tản nhiệt', N'DeepCool LS520', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (738, N'Mainboard', N'Gigabyte B550', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (738, N'Vỏ case', N'Cooler Master', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (738, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (739, N'Mainboard', N'ASRock Z790', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (739, N'Vỏ case', N'Jonsbo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (739, N'Tản nhiệt', N'Thermalright Frozen Warframe 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (740, N'Mainboard', N'ASUS B650', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (740, N'Vỏ case', N'Vitra', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (740, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (741, N'Mainboard', N'MSI Z790', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (741, N'Vỏ case', N'Aigo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (741, N'Tản nhiệt', N'DeepCool LS520', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (742, N'Mainboard', N'Gigabyte X670', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (742, N'Vỏ case', N'Xigmatek', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (742, N'Tản nhiệt', N'Cooler Master MasterLiquid 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (743, N'Mainboard', N'ASRock Z790', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (743, N'Vỏ case', N'DarkFlash', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (743, N'Tản nhiệt', N'Thermalright Frozen Warframe 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (744, N'Mainboard', N'ASUS X670', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (744, N'Vỏ case', N'Corsair', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (744, N'Tản nhiệt', N'ID-Cooling FROZN 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (745, N'Mainboard', N'MSI B560', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (745, N'Vỏ case', N'Cooler Master', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (745, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (746, N'Mainboard', N'Gigabyte A520', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (746, N'Vỏ case', N'Jonsbo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (746, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (747, N'Mainboard', N'ASRock B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (747, N'Vỏ case', N'Vitra', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (747, N'Tản nhiệt', N'ID-Cooling SE-224', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (748, N'Mainboard', N'ASUS B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (748, N'Vỏ case', N'Aigo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (748, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (749, N'Mainboard', N'MSI Z790', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (749, N'Vỏ case', N'Xigmatek', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (749, N'Tản nhiệt', N'DeepCool LS520', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (750, N'Mainboard', N'Gigabyte X670', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (750, N'Vỏ case', N'DarkFlash', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (750, N'Tản nhiệt', N'Cooler Master MasterLiquid 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (751, N'Mainboard', N'ASRock Z790', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (751, N'Vỏ case', N'Corsair', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (751, N'Tản nhiệt', N'Thermalright Frozen Warframe 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (752, N'Mainboard', N'ASUS Z790', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (752, N'Vỏ case', N'Cooler Master', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (752, N'Tản nhiệt', N'ID-Cooling FROZN 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (753, N'Mainboard', N'MSI X670', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (753, N'Vỏ case', N'Jonsbo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (753, N'Tản nhiệt', N'DeepCool LS520', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (754, N'Mainboard', N'Gigabyte Z790', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (754, N'Vỏ case', N'Vitra', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (754, N'Tản nhiệt', N'Cooler Master MasterLiquid 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (755, N'Mainboard', N'ASRock B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (755, N'Vỏ case', N'Aigo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (755, N'Tản nhiệt', N'ID-Cooling SE-224', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (756, N'Mainboard', N'ASUS A520', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (756, N'Vỏ case', N'Xigmatek', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (756, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (757, N'Mainboard', N'MSI B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (757, N'Vỏ case', N'DarkFlash', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (757, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (758, N'Mainboard', N'Gigabyte B650', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (758, N'Vỏ case', N'Corsair', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (758, N'Tản nhiệt', N'DeepCool AK400', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (759, N'Mainboard', N'ASRock A520', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (759, N'Vỏ case', N'Cooler Master', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (759, N'Tản nhiệt', N'ID-Cooling SE-224', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (760, N'Mainboard', N'ASUS B760', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (760, N'Vỏ case', N'Jonsbo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (760, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (761, N'Mainboard', N'MSI B650', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (761, N'Vỏ case', N'Vitra', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (761, N'Tản nhiệt', N'Tản nhiệt zin theo CPU', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (762, N'Mainboard', N'Gigabyte Z790', 90);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (762, N'Vỏ case', N'Aigo', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (762, N'Tản nhiệt', N'Cooler Master MasterLiquid 240', 92);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (764, N'Vỏ case', N'DarkFlash', 91);
INSERT INTO PRODUCT_SPEC (product_id, spec_key, spec_value, sort_order) VALUES (764, N'Tản nhiệt', N'ID-Cooling FROZN 240', 92);
GO
